### PR TITLE
Add filtering for started games

### PR DESCRIPTION
**Pull request by G07cha**
Now if game started it won't show in games list

Resolves bloxparty/bloxparty#34

### CODE REVIEW

**Comment by G07cha** [comment]
Travis build seems broken.

**Comment by kvnneff** [comment]
Thanks but rather than hide games that are in progress I'd like to always display all games on the client, though if there are 6 players I want to disable joining that room and gray it out on the list of games.  If a game is in session I'd still like to allow players to join and watch but they'll have to wait until someone wins the current game and starts the next one before they can play.  

If my friends are in a game room and they have a game started I'd still like to be able to join the room and wait until the next game starts.  Games usually only last a few minutes anyway, especially once the special blocks are implemented.

So I don't want to hide anything, but it should be made obvious when a game is in currently in play and when a room is full.

**Comment by G07cha** [comment]
It's just based on my impression of last stress test when peoples just joining to rooms and yelling that they can't play(they also showing as opponents and receiving garbage lines)

**Comment by kvnneff** [comment]
I posted a new issue #3 for new opponents receiving garbage lines.  Also posted bloxparty/bloxparty#38 and bloxparty/bloxparty#37 for UI enhancements to help players know what's going on.

**Comment by G07cha** [comment]
@kvnneff, thank you, now I understand what you would like to see.

**Pull request closed without merging**
